
# Set which leading flux to use
flux: "efiitg_gb"

# Use pre-trained model or train from scratch
pretrained:
  Classifier:
      efiitg_gb:
          save_path: /path/to/Classifier_model.pt
          trained: True
      efetem_gb:
          save_path: /path/to/Classifier_model.pt
          trained: True
      efeetg_gb:
          save_path: /path/to/Classifier_model.pt
          trained: True
  Regressor:
      efiitg_gb:
          save_path: /path/to/Regressor_model.pt
          trained: True
      efetem_gb:
          save_path: /path/to/Regressor_model.pt
          trained: True
      efeetg_gb:
          save_path: /path/to/Regressor_model.pt
          trained: True

# Path to data used for training and validation
data:
  train: /path/to/train/data
  validation: /path/to/validation/data


save_paths:
  plots: /path/to/save/plots
  outputs: /path/to/save/outputs

retrain_classifier: False
retrain_regressor: True

logging_level: DEBUG

# Pipeline parameters
iterations: 3
initial_epochs: 25
MC_dropout_runs: 50
keep_prob: 0.25 
patience: 25
lambda: 0.6
learning_rate: 0.001

# if training models from scratch, the hyperparameters below are used
train_epochs: 25
train_patience: 33

