pretrained:
  ITG_class:
    trained: True 
    save_path: "/home/tmadula/UKAEAGroupProject/src/notebooks/classifier_model.pt"
  ITG_reg: 
    trained: True 
    save_path: "/home/tmadula/UKAEAGroupProject/src/notebooks/regression_model.pt"

data:
  train: "/home/tmadula/data/UKAEA/train_data_clipped.pkl"
  validation: "/home/tmadula/data/UKAEA/valid_data_clipped.pkl"

save_paths:
  plots: "/home/tmadula/plots/"
  outputs: "/home/tmadula/submit/outputs/"

retrain_classifier: False
retrain_regressor: True

# Pipeline parameters
iterations: 5
initial_epochs: 50
MC_dropout_runs: 15
keep_prob: 0.25 
