pretrained:
  Classifier:
    trained: True 
    save_path: "/share/rcifdata/jbarr/UKAEAGroupProject/src/notebooks/classifier_model.pt"
  Regressor: 
    trained: True 
    save_path: "/share/rcifdata/jbarr/UKAEAGroupProject/src/notebooks/regression_model.pt"

data:
  train: "/home/tmadula/data/UKAEA/train_data_clipped.pkl"
  validation: "/home/tmadula/data/UKAEA/valid_data_clipped.pkl"

save_paths:
  plots: "/home/tmadula/submit/plots/"
  outputs: "/home/tmadula/submit/out/"

retrain_classifier: False
retrain_regressor: True

logging_level: DEBUG

# Pipeline parameters
iterations: 5
initial_epochs: 200
MC_dropout_runs: 50
keep_prob: 0.25 
patience: 10
lambda: 0.2
learning_rate: 0.001

# if training models from scratch, the hyperparameters below are used
train_epochs: 25
train_patience: 33
